version: '3'


services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: cc_test_django
    depends_on:
      - minio
      - postgres
      - redis
    environment:
      DJANGO_AWS_ACCESS_KEY_ID: minioadmin
      DJANGO_AWS_SECRET_ACCESS_KEY: minioadmin
      DJANGO_AWS_S3_ENDPOINT_URL: http://minio:9000
      DJANGO_AWS_S3_ENDPOINT_LOCAL_DOMAIN: 0.0.0.0:9000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: cleancar_test_db
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
      REDIS_URL: redis://redis:6379/0

    ports:
      - "80:80"
    command: bash -c "pytest -s --disable-warnings"

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    container_name: cc_test_postgres
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: cleancar_test_db
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug

  redis:
    image: redis:6
    container_name: cc_test_redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    build:
      context: .
      dockerfile: ./compose/minio/Dockerfile
    container_name: cc_test_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 20s
      retries: 3
    entrypoint: ./entrypoint
