# Generated by Django 5.1.6 on 2025-03-11 18:06

import app.utils.storages
import app.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=app.utils.utils.get_str_uuid, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, storage=app.utils.storages.MediaStorage(), upload_to='files/images/')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'images',
            },
        ),
    ]
